#! /bin/bash -e

if test "$1" = '--help'; then echo "\
Usage:
  $(basename $0)

  We’ll parse your Readme.md and render a manpage at \`/manpages/please.1\`.
  As well as that, we’ll render a plain-text fallback
  at \`/manpages/please.1.txt\` – for those of us stuck on Windows.
"; exit; fi

cd "$(dirname "$0")"/..
mkdir -p manpages
rm -rf manpages/*

# 1. Render the manpage
#   * Strip everything before the title
#   * Make the title marked-man-friendly
#   * Strip the INSTALLATION guide (whoever is reading the manpage
#     has installed it already)
#   * Strip HTML tags
#   * Make sure the SYNOPSIS doesn’t look shitty
#   * Replace characters marked-man doesn’t like
#   * Render
cat Readme.md \
  | perl -0777 -pe 's|^[\S\s]*?\n(<h1\b)|$1|' \
  | perl -0777 -pe 's|^<h1\b[^>]*>[^<]*<img\b[^>]*alt="([^"]+) – ([^"]+)"[^>]*/>[^<]*</h1>|# $1(1) -- $2|' \
  | perl -0777 -pe 's|\n## INSTALLATION[\S\s]*?(?=\n## )||' \
  | perl -0777 -pe 's#</?(?:a|p|img)[\S\s]*?>##g' \
  | perl -0777 -pe 's|```sh\n([\S\s]*?\n)```\n|$1|' \
  | sed 's/[“”]/"/g' | sed "s/’/'/g" \
  | ./node_modules/.bin/marked-man \
    --version=v$(node -p 'require("./package.json").version') \
  > manpages/please.1

# 2. Render the plain-text fallback
#   * Limit line width to 80 chars
#   * Render with man
#   * Collapse consecutive blank lines (matches default behavior)
MANWIDTH=80 \
man manpages/please.1 \
  | perl -0777 -pe 's/\n{2,}/\n\n/g' \
  > manpages/please.1.txt
